[[Gumbo]]
arch = "aarch64"
git-tree-sha1 = "5fee3553325d17d336902bf6f1529b75a4987614"
os = "macos"

    [[Gumbo.download]]
    sha256 = "2b1cef9467f2ad70a5b4ae7eb5de2a9fd105922d5332e2600d76c5fe96436349"
    url = "https://github.com/JuliaBinaryWrappers/Gumbo_jll.jl/releases/download/Gumbo-v0.10.2+0/Gumbo.v0.10.2.aarch64-apple-darwin.tar.gz"
[[Gumbo]]
arch = "aarch64"
git-tree-sha1 = "fbb0ced402c730717e9f6a0d28bc0cb315e0f5d7"
libc = "glibc"
os = "linux"

    [[Gumbo.download]]
    sha256 = "f2e8d26b9ef797c18f873b725ae09e794256f7fb36e36f81c0ba6dd7d70d062c"
    url = "https://github.com/JuliaBinaryWrappers/Gumbo_jll.jl/releases/download/Gumbo-v0.10.2+0/Gumbo.v0.10.2.aarch64-linux-gnu.tar.gz"
[[Gumbo]]
arch = "aarch64"
git-tree-sha1 = "ea93f3da49a8e11761d36ae99ff9b492a17e9dea"
libc = "musl"
os = "linux"

    [[Gumbo.download]]
    sha256 = "b6c3c7ba672b40ef33ab35b5a2e0efa2c8b555ed0c886951baaa22c41858a05d"
    url = "https://github.com/JuliaBinaryWrappers/Gumbo_jll.jl/releases/download/Gumbo-v0.10.2+0/Gumbo.v0.10.2.aarch64-linux-musl.tar.gz"
[[Gumbo]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "90b1931e3fe7b2bc2df66685edc7f05d1a04acb9"
libc = "glibc"
os = "linux"

    [[Gumbo.download]]
    sha256 = "082780acc35ae41cfaf19e4385f9d694e5f1d6c9f0a52a1b4804dd39ad66241f"
    url = "https://github.com/JuliaBinaryWrappers/Gumbo_jll.jl/releases/download/Gumbo-v0.10.2+0/Gumbo.v0.10.2.armv6l-linux-gnueabihf.tar.gz"
[[Gumbo]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "786b6b078571d8e2dcee3c2ed64a0f15a9feec2e"
libc = "musl"
os = "linux"

    [[Gumbo.download]]
    sha256 = "8d33503eff037de8a99c02b5dc908e8a5f4cd573893f3e3e7692404687a6bde0"
    url = "https://github.com/JuliaBinaryWrappers/Gumbo_jll.jl/releases/download/Gumbo-v0.10.2+0/Gumbo.v0.10.2.armv6l-linux-musleabihf.tar.gz"
[[Gumbo]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b88bc415710b4d806fd588da8ba04b91a4e2d514"
libc = "glibc"
os = "linux"

    [[Gumbo.download]]
    sha256 = "441f91869e0d56986fd56ebbc0f0aa48a615c0cc480fdda176a0732f260ca4cc"
    url = "https://github.com/JuliaBinaryWrappers/Gumbo_jll.jl/releases/download/Gumbo-v0.10.2+0/Gumbo.v0.10.2.armv7l-linux-gnueabihf.tar.gz"
[[Gumbo]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8cbcc9222a555a0399ffae65eaeec99949c3e697"
libc = "musl"
os = "linux"

    [[Gumbo.download]]
    sha256 = "97b6cfde20cd764ff0f54bf8cbba138b9b888be24ff52a606d6dc4c704ccd02f"
    url = "https://github.com/JuliaBinaryWrappers/Gumbo_jll.jl/releases/download/Gumbo-v0.10.2+0/Gumbo.v0.10.2.armv7l-linux-musleabihf.tar.gz"
[[Gumbo]]
arch = "i686"
git-tree-sha1 = "a91d2c848c04fd5c12902e698498aa68aa9dd1bc"
libc = "glibc"
os = "linux"

    [[Gumbo.download]]
    sha256 = "313e1d69c0a408625273e792f836fdbee9992cf2b368d3f473b331e6ddacfbc2"
    url = "https://github.com/JuliaBinaryWrappers/Gumbo_jll.jl/releases/download/Gumbo-v0.10.2+0/Gumbo.v0.10.2.i686-linux-gnu.tar.gz"
[[Gumbo]]
arch = "i686"
git-tree-sha1 = "0333d5aff845c95bbde45e4f4f9c52c1d8349c19"
libc = "musl"
os = "linux"

    [[Gumbo.download]]
    sha256 = "b58f67b413345a76d6712a8f8957ec9b8e2ccce13cf00e2f2d44d3cda0fe9731"
    url = "https://github.com/JuliaBinaryWrappers/Gumbo_jll.jl/releases/download/Gumbo-v0.10.2+0/Gumbo.v0.10.2.i686-linux-musl.tar.gz"
[[Gumbo]]
arch = "i686"
git-tree-sha1 = "f03e881530b104b09b11bbd6c5c94667aa2763e0"
os = "windows"

    [[Gumbo.download]]
    sha256 = "2d1c4d963e7bf996c055879dfb705c7eabaede9cad0ab484a2f94cda5da783d4"
    url = "https://github.com/JuliaBinaryWrappers/Gumbo_jll.jl/releases/download/Gumbo-v0.10.2+0/Gumbo.v0.10.2.i686-w64-mingw32.tar.gz"
[[Gumbo]]
arch = "powerpc64le"
git-tree-sha1 = "fe58a813730b658e0f5a1e1aeadc20c20c3b19b1"
libc = "glibc"
os = "linux"

    [[Gumbo.download]]
    sha256 = "31e6e563d5e6f0759eab1e8d2d6f193435a4231ca671390c7de14264f2120c43"
    url = "https://github.com/JuliaBinaryWrappers/Gumbo_jll.jl/releases/download/Gumbo-v0.10.2+0/Gumbo.v0.10.2.powerpc64le-linux-gnu.tar.gz"
[[Gumbo]]
arch = "x86_64"
git-tree-sha1 = "cac8e280af8113787ab7605cc082a8c1610a76d5"
os = "macos"

    [[Gumbo.download]]
    sha256 = "830c0470c358e426f513c92907d31970cf2a165f6afb6299bf182c1404911bc8"
    url = "https://github.com/JuliaBinaryWrappers/Gumbo_jll.jl/releases/download/Gumbo-v0.10.2+0/Gumbo.v0.10.2.x86_64-apple-darwin.tar.gz"
[[Gumbo]]
arch = "x86_64"
git-tree-sha1 = "ac1f1270ab0df7a7d497730684560b50f0efb7ae"
libc = "glibc"
os = "linux"

    [[Gumbo.download]]
    sha256 = "3bb536357851e4f7fbeb9dd54223f11a57a39c637094a86c8462a9acac50797f"
    url = "https://github.com/JuliaBinaryWrappers/Gumbo_jll.jl/releases/download/Gumbo-v0.10.2+0/Gumbo.v0.10.2.x86_64-linux-gnu.tar.gz"
[[Gumbo]]
arch = "x86_64"
git-tree-sha1 = "3e0c20a8d6f3f9b80ac5beebf2a3fb90e67f6b20"
libc = "musl"
os = "linux"

    [[Gumbo.download]]
    sha256 = "fa15d7584ea7dc31adf8ec6a4bce8d02713a3386e8c448c6cc6e18ef65137ed0"
    url = "https://github.com/JuliaBinaryWrappers/Gumbo_jll.jl/releases/download/Gumbo-v0.10.2+0/Gumbo.v0.10.2.x86_64-linux-musl.tar.gz"
[[Gumbo]]
arch = "x86_64"
git-tree-sha1 = "ef364715fff2145298c95d726cb4d8e35fd6f654"
os = "freebsd"

    [[Gumbo.download]]
    sha256 = "a7d92d3388126b78d74d3ac9d8f5573a5771d906db6a6fb22da37e32d168af48"
    url = "https://github.com/JuliaBinaryWrappers/Gumbo_jll.jl/releases/download/Gumbo-v0.10.2+0/Gumbo.v0.10.2.x86_64-unknown-freebsd.tar.gz"
[[Gumbo]]
arch = "x86_64"
git-tree-sha1 = "c8080c7680d33a25d3e774ead8b6ea141c20f40f"
os = "windows"

    [[Gumbo.download]]
    sha256 = "00258389035087672fffce40118fa1d362c543b68d474f6c62b758cfadc3260f"
    url = "https://github.com/JuliaBinaryWrappers/Gumbo_jll.jl/releases/download/Gumbo-v0.10.2+0/Gumbo.v0.10.2.x86_64-w64-mingw32.tar.gz"
