[[Gumbo]]
arch = "armv7l"
git-tree-sha1 = "bc6953552b900b38dc84cf45c7b32f4d70f69cb9"
libc = "glibc"
os = "linux"

    [[Gumbo.download]]
    sha256 = "2446598598df8e3e48f31d75ecfb1d0fb66ab448473844c5d518df1bc6449431"
    url = "https://github.com/JuliaBinaryWrappers/Gumbo_jll.jl/releases/download/Gumbo-v0.10.1+0/Gumbo.v0.10.1.arm-linux-gnueabihf.tar.gz"
[[Gumbo]]
arch = "x86_64"
git-tree-sha1 = "07b0220a7eb1c82405955fc39cc1d84881992489"
libc = "glibc"
os = "linux"

    [[Gumbo.download]]
    sha256 = "9f1e65e62296b6ac940a142ac8b8660f8a89b55a4ccfd9e3efdf50738441048d"
    url = "https://github.com/JuliaBinaryWrappers/Gumbo_jll.jl/releases/download/Gumbo-v0.10.1+0/Gumbo.v0.10.1.x86_64-linux-gnu.tar.gz"
[[Gumbo]]
arch = "aarch64"
git-tree-sha1 = "3ccad97ab294846457f813a55f1ed12afd25ff28"
libc = "musl"
os = "linux"

    [[Gumbo.download]]
    sha256 = "e0a8479576d57eb960b825b87c255321ea3f424ba84dd237d61ff73ba0002bad"
    url = "https://github.com/JuliaBinaryWrappers/Gumbo_jll.jl/releases/download/Gumbo-v0.10.1+0/Gumbo.v0.10.1.aarch64-linux-musl.tar.gz"
[[Gumbo]]
arch = "powerpc64le"
git-tree-sha1 = "efbed159e60735603aa3835f74970127ed3e934a"
libc = "glibc"
os = "linux"

    [[Gumbo.download]]
    sha256 = "be11bf8eaf1405c9a4cc2a2b1cc0e21fc211d019880497a21181de9a271a56fe"
    url = "https://github.com/JuliaBinaryWrappers/Gumbo_jll.jl/releases/download/Gumbo-v0.10.1+0/Gumbo.v0.10.1.powerpc64le-linux-gnu.tar.gz"
[[Gumbo]]
arch = "x86_64"
git-tree-sha1 = "bd995d018a6696802cd4f685a017046bfa887dc2"
os = "macos"

    [[Gumbo.download]]
    sha256 = "b07d472d562fbd42e542e9e6472d42b3facf9e7ff948448646448d5b73f8adab"
    url = "https://github.com/JuliaBinaryWrappers/Gumbo_jll.jl/releases/download/Gumbo-v0.10.1+0/Gumbo.v0.10.1.x86_64-apple-darwin14.tar.gz"
[[Gumbo]]
arch = "x86_64"
git-tree-sha1 = "ba3bf3023c23a830260fce697c665f98d1615d87"
libc = "musl"
os = "linux"

    [[Gumbo.download]]
    sha256 = "32d6da4e980596884667fbcc80dd273fe6bbbf325f2e115b6ac668d11c62a401"
    url = "https://github.com/JuliaBinaryWrappers/Gumbo_jll.jl/releases/download/Gumbo-v0.10.1+0/Gumbo.v0.10.1.x86_64-linux-musl.tar.gz"
[[Gumbo]]
arch = "x86_64"
git-tree-sha1 = "28893fac0028e8491ff7810a98ff49071c971903"
os = "windows"

    [[Gumbo.download]]
    sha256 = "5cc91676fe48b4bb0082e96ad7607731f643ae44986edf152f25702caa54758f"
    url = "https://github.com/JuliaBinaryWrappers/Gumbo_jll.jl/releases/download/Gumbo-v0.10.1+0/Gumbo.v0.10.1.x86_64-w64-mingw32.tar.gz"
[[Gumbo]]
arch = "i686"
git-tree-sha1 = "a54ad151921006dcbceba7816612859cd9e3cc35"
libc = "glibc"
os = "linux"

    [[Gumbo.download]]
    sha256 = "37ea94ffcf9293041d0430d7c7d6c868f0f83b96db31f5a58afee09eaa614990"
    url = "https://github.com/JuliaBinaryWrappers/Gumbo_jll.jl/releases/download/Gumbo-v0.10.1+0/Gumbo.v0.10.1.i686-linux-gnu.tar.gz"
[[Gumbo]]
arch = "aarch64"
git-tree-sha1 = "83e9b05eaddc64305ffbc9a218d1272be667fac8"
libc = "glibc"
os = "linux"

    [[Gumbo.download]]
    sha256 = "596f2df22e17fcdcc3e043d493ace953b9a7ff8efbfecd071aee77bd07fd60e9"
    url = "https://github.com/JuliaBinaryWrappers/Gumbo_jll.jl/releases/download/Gumbo-v0.10.1+0/Gumbo.v0.10.1.aarch64-linux-gnu.tar.gz"
[[Gumbo]]
arch = "i686"
git-tree-sha1 = "7415008683d1cacc707de134c659e1a75a5f841c"
libc = "musl"
os = "linux"

    [[Gumbo.download]]
    sha256 = "5e5c45d01aa13aa8c09a2e09e2efae88b8749544dd5183f4835544173ef4ccc9"
    url = "https://github.com/JuliaBinaryWrappers/Gumbo_jll.jl/releases/download/Gumbo-v0.10.1+0/Gumbo.v0.10.1.i686-linux-musl.tar.gz"
[[Gumbo]]
arch = "x86_64"
git-tree-sha1 = "6a57df2287cc7c85983fd6007d9954740a92b0e8"
os = "freebsd"

    [[Gumbo.download]]
    sha256 = "bd7e20faf02d12e752fbffc6953b30e16678ea3d4af6d0f78a5b1365171bc5f2"
    url = "https://github.com/JuliaBinaryWrappers/Gumbo_jll.jl/releases/download/Gumbo-v0.10.1+0/Gumbo.v0.10.1.x86_64-unknown-freebsd11.1.tar.gz"
[[Gumbo]]
arch = "i686"
git-tree-sha1 = "9196fcd22b37ce71ea89efba7066988334b5d12c"
os = "windows"

    [[Gumbo.download]]
    sha256 = "b38fe3f73d6b892aecb44ef06ceeab5d13348805e81faa3e357aaf2b1b0b4f08"
    url = "https://github.com/JuliaBinaryWrappers/Gumbo_jll.jl/releases/download/Gumbo-v0.10.1+0/Gumbo.v0.10.1.i686-w64-mingw32.tar.gz"
[[Gumbo]]
arch = "armv7l"
git-tree-sha1 = "fae3bbddf5d0dac172426fe3a220d6e0bd557032"
libc = "musl"
os = "linux"

    [[Gumbo.download]]
    sha256 = "9a6079ef8e5cc626861c503ff47fa0cfc35c77ccf88187c390f5f5ed00497239"
    url = "https://github.com/JuliaBinaryWrappers/Gumbo_jll.jl/releases/download/Gumbo-v0.10.1+0/Gumbo.v0.10.1.arm-linux-musleabihf.tar.gz"
