[[Gumbo]]
arch = "aarch64"
git-tree-sha1 = "a8d06f69e8400866b5f788dc02a5025f58dacd0e"
libc = "glibc"
os = "linux"

    [[Gumbo.download]]
    sha256 = "bea39871e3f58fd4d98f9a4090ec0c1d3713d78bc9f5f3c4089f1c8425641543"
    url = "https://github.com/JuliaBinaryWrappers/Gumbo_jll.jl/releases/download/Gumbo-v0.10.1+1/Gumbo.v0.10.1.aarch64-linux-gnu.tar.gz"
[[Gumbo]]
arch = "aarch64"
git-tree-sha1 = "484b6874b36ec4dcfb602048490f7e7e4aa41fd9"
libc = "musl"
os = "linux"

    [[Gumbo.download]]
    sha256 = "e64801803a032efab8c93e1f9a577dda8d2916b4db901c1ad0d027fe9851248d"
    url = "https://github.com/JuliaBinaryWrappers/Gumbo_jll.jl/releases/download/Gumbo-v0.10.1+1/Gumbo.v0.10.1.aarch64-linux-musl.tar.gz"
[[Gumbo]]
arch = "armv7l"
git-tree-sha1 = "bfaf657961cbdccad85deb82c81902cd0f420f70"
libc = "glibc"
os = "linux"

    [[Gumbo.download]]
    sha256 = "f5cd6aa5831ad062b22688fd5aad0118469c03418e10468f12ff473615e23607"
    url = "https://github.com/JuliaBinaryWrappers/Gumbo_jll.jl/releases/download/Gumbo-v0.10.1+1/Gumbo.v0.10.1.armv7l-linux-gnueabihf.tar.gz"
[[Gumbo]]
arch = "armv7l"
git-tree-sha1 = "da0a545e83020a6d56d55815dccee34934c125fa"
libc = "musl"
os = "linux"

    [[Gumbo.download]]
    sha256 = "13e30192dc30d2043629c432839a271e3d1512100165018c7aa01b6c43cfdab7"
    url = "https://github.com/JuliaBinaryWrappers/Gumbo_jll.jl/releases/download/Gumbo-v0.10.1+1/Gumbo.v0.10.1.armv7l-linux-musleabihf.tar.gz"
[[Gumbo]]
arch = "i686"
git-tree-sha1 = "146897e12d04cc15d9818c1d14e5bb980a6bb87b"
libc = "glibc"
os = "linux"

    [[Gumbo.download]]
    sha256 = "2b0aaad167dda4a3a690fa1fa552908160de83cfe9e4f0fe5ed689bebfa72862"
    url = "https://github.com/JuliaBinaryWrappers/Gumbo_jll.jl/releases/download/Gumbo-v0.10.1+1/Gumbo.v0.10.1.i686-linux-gnu.tar.gz"
[[Gumbo]]
arch = "i686"
git-tree-sha1 = "2e66d774dddcce82a79bd490353a7845c64b1c02"
libc = "musl"
os = "linux"

    [[Gumbo.download]]
    sha256 = "8646eae70afdc94da04cff2a1c47227b77644f276cd1faa40f5234ce21ab8eb2"
    url = "https://github.com/JuliaBinaryWrappers/Gumbo_jll.jl/releases/download/Gumbo-v0.10.1+1/Gumbo.v0.10.1.i686-linux-musl.tar.gz"
[[Gumbo]]
arch = "i686"
git-tree-sha1 = "1d7af93d3d532f05afe9624f9d8700517611eb0e"
os = "windows"

    [[Gumbo.download]]
    sha256 = "95b5c53c3588cd6b72bad24985a02962eb90db1b6c7d51b88720e0211d2be414"
    url = "https://github.com/JuliaBinaryWrappers/Gumbo_jll.jl/releases/download/Gumbo-v0.10.1+1/Gumbo.v0.10.1.i686-w64-mingw32.tar.gz"
[[Gumbo]]
arch = "powerpc64le"
git-tree-sha1 = "f2ee665b5423cc6b0effcf0a8f5f00999a48eb87"
libc = "glibc"
os = "linux"

    [[Gumbo.download]]
    sha256 = "6b53cca1a0a22a9594eb9f2059aaf3a0f8079b85a97dd4039a2841afaee2713f"
    url = "https://github.com/JuliaBinaryWrappers/Gumbo_jll.jl/releases/download/Gumbo-v0.10.1+1/Gumbo.v0.10.1.powerpc64le-linux-gnu.tar.gz"
[[Gumbo]]
arch = "x86_64"
git-tree-sha1 = "69e59b18b8ec05d045b689aa5543bfed8786b8a5"
os = "macos"

    [[Gumbo.download]]
    sha256 = "6f8eb2fe37d3ed84530b38534d7e038d33615f1fa58df8b37d570038f4c62c04"
    url = "https://github.com/JuliaBinaryWrappers/Gumbo_jll.jl/releases/download/Gumbo-v0.10.1+1/Gumbo.v0.10.1.x86_64-apple-darwin14.tar.gz"
[[Gumbo]]
arch = "x86_64"
git-tree-sha1 = "6f61b22bbbd3e4627668d0b751ee88b57f724746"
libc = "glibc"
os = "linux"

    [[Gumbo.download]]
    sha256 = "20ed653f13f3b50fecc6136b16845b4446fa23dba0f3c10006db39e7f187c246"
    url = "https://github.com/JuliaBinaryWrappers/Gumbo_jll.jl/releases/download/Gumbo-v0.10.1+1/Gumbo.v0.10.1.x86_64-linux-gnu.tar.gz"
[[Gumbo]]
arch = "x86_64"
git-tree-sha1 = "ab92459695f60228625bb2a13a522e1923707b5d"
libc = "musl"
os = "linux"

    [[Gumbo.download]]
    sha256 = "aaf2d6be898c90d78d98d4a24935ea98af6889fb39373eb2f0a66b701d81fd7d"
    url = "https://github.com/JuliaBinaryWrappers/Gumbo_jll.jl/releases/download/Gumbo-v0.10.1+1/Gumbo.v0.10.1.x86_64-linux-musl.tar.gz"
[[Gumbo]]
arch = "x86_64"
git-tree-sha1 = "1bedbe8dfc5f29fe5527869bbe05e6d9e58ad44c"
os = "freebsd"

    [[Gumbo.download]]
    sha256 = "8694170afe93e2eaa2d1026469119d6325a3fdbcdcc77424ddde241ffcd8f8ad"
    url = "https://github.com/JuliaBinaryWrappers/Gumbo_jll.jl/releases/download/Gumbo-v0.10.1+1/Gumbo.v0.10.1.x86_64-unknown-freebsd11.1.tar.gz"
[[Gumbo]]
arch = "x86_64"
git-tree-sha1 = "d80d7558e2ad6b2915b07733d964af5989e7fd20"
os = "windows"

    [[Gumbo.download]]
    sha256 = "0513bcc67f2467c088ef8957ffc3e4fc6c174f7f7e66be9c0e8b8ef1b71a3ba0"
    url = "https://github.com/JuliaBinaryWrappers/Gumbo_jll.jl/releases/download/Gumbo-v0.10.1+1/Gumbo.v0.10.1.x86_64-w64-mingw32.tar.gz"
