# Autogenerated wrapper script for Gumbo_jll for aarch64-apple-darwin
export libgumbo

JLLWrappers.@generate_wrapper_header("Gumbo")
JLLWrappers.@declare_library_product(libgumbo, "@rpath/libgumbo.1.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libgumbo,
        "lib/libgumbo.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
